development:
  adapter: postgresql
  encoding: unicode
  database: rails_heroku_db_development
  pool: 5 
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: rails_heroku_db_test
  pool: 5 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails_heroku_db_production
  pool: 5 
  password:
